#Copyright (c) Microsoft Corporation. All rights reserved.
#Licensed under the MIT License.
#Building and packaging the artifacts of the Java-SDK libraries using the build.gradle file.
#Ready the package for deployment and release. 

trigger:
  branches:
    include:
    - dev
  paths: 
    include:
      - src/*
    exclude:
      - docs/*
      - .github/*
      - LICENSE
      - .gitignore
      - README-localized/*
      - CONTRIBUTING.md
      - THIRD PARTY NOTICES
      - README.md

pr: none

pool:
  vmImage: ubuntu-latest

steps: 
- template: templates/secure-files.yml
- template: templates/build-and-coverage.yml
- template: templates/publish-artifacts.yml
- template: templates/alert-failure.yml


